cpuf: Update
Signed-off-by: MOVZX <movzx@yahoo.com>

diff --git a/Bins/cpuf b/Bins/cpuf
--- a/Bins/cpuf
+++ b/Bins/cpuf
@@ -1,32 +1,38 @@
 #!/usr/bin/env bash
 
-LC_NUMERIC="en_GB.UTF-8"
+LC_NUMERIC="en_GB.UTF-8"  # For consistent numeric formatting
 
-# Read temperatures and power
-CPU_TCTL=$(cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon7/temp1_input)
-CPU_TCCD=$(cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon7/temp3_input)
-CPU_POWER=$(/usr/local/bin/ryzen)
+# Read Temperatures and Power
+HWMON_PATH=$(grep -l 'k10temp' /sys/class/hwmon/hwmon*/name)
 
-# Convert temperatures to Celsius
-CPU_TCTL=$((CPU_TCTL / 1000))
-CPU_TCCD=$((CPU_TCCD / 1000))
+if [ -n "$HWMON_PATH" ]; then
+    CPU_TCTL=$(cat "${HWMON_PATH%/name}/temp1_input")
+    CPU_TCCD=$(cat "${HWMON_PATH%/name}/temp3_input")
+    CPU_TCTL=$((CPU_TCTL / 1000))
+    CPU_TCCD=$((CPU_TCCD / 1000))
+    CPU_POWER=$(/usr/local/bin/ryzen)
+else
+    echo "k10temp sensor not found."
 
-# Collect CPU frequencies
+    exit 1
+fi
+
+# Collect CPU Frequencies
 for i in {0..15}; do
     CPU_FREQ[$i]=$(cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_cur_freq)
-    CPU_FREQ[$i]=$((CPU_FREQ[$i] / 1000)) # Convert to MHz
+    CPU_FREQ[$i]=$((CPU_FREQ[$i] / 1000))
 done
 
-# Output data
+# Output Data
 echo ""
 echo "Ryzen 7 7800X3D"
 echo ""
-printf "Tctl    : %11.40s\n" "$CPU_TCTL °C"
-printf "Tccd    : %11.40s\n" "$CPU_TCCD °C"
-printf "Power   : %10.40s\n" "$CPU_POWER W"
+printf "Tctl    : %7d °C\n" "$CPU_TCTL"
+printf "Tccd    : %7d °C\n" "$CPU_TCCD"
+printf "Power   : %8.2f W\n" "$CPU_POWER"
 echo ""
 
-# Output CPU frequencies
+# Output CPU Frequencies
 for i in {0..15}; do
-    printf "CPU %2d  : %10.40s\n" "$((i + 1))" "${CPU_FREQ[$i]} MHz"
+    printf "CPU %2d  : %6d MHz\n" "$((i + 1))" "${CPU_FREQ[$i]}"
 done
